version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget.exe restore seq.app.teams.sln
build:
  project: Seq.App.Teams.sln
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: dwfJiNVOKfmWObkUb9Kbx6MyuzP5kEbAE6RhxFrAfZ7ArJk77BN3voyogX7yh/W1
  on:
    branch: master
