version: '{build}'
skip_tags: true
image: Visual Studio 2019
install:
build_script:
  - ps: ./Build.ps1
test: off
deploy:
- provider: NuGet
  api_key:
    secure: dwfJiNVOKfmWObkUb9Kbx6MyuzP5kEbAE6RhxFrAfZ7ArJk77BN3voyogX7yh/W1
  on:
    branch: master
